app = "photonic-next-staging-redis"
primary_region = "ams"

[build]
  image = "flyio/redis:6.2.6"

[[mounts]]
  source = "photonic_next_staging_redis_v"
  destination = "/data"

[[services]]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  protocol = "tcp"
  internal_port = 6379

  [[services.ports]]
    port = 10000

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    restart_limit = 0

[metrics]
  port = 9091
  path = "/metrics"
